name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true
      - run: go version
      - name: Run build
        run: make clean build
      - name: Run test
        run: make test.race
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build base
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          build-args: |
            MAKE_TARGET=test build
      - name: Docker build all
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          build-args: |
            MAKE_TARGET=all
